# Generated by Django 5.1.1 on 2024-09-03 22:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nex_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="user",
        ),
        migrations.AlterField(
            model_name="tokenuser",
            name="token",
            field=models.CharField(
                default="36b16c7ea0aa41c0a9dcea37f9ef1443", max_length=64, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ]
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("end_date", models.DateField()),
                ("private_key", models.CharField(max_length=63, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="nex_app.nexuser",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="ipconfig",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nex_app.device",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("user", "num"), name="unique_user_num"
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
